language: python
python:
  - "3.3.6"
# command to install dependencies
install:
  - python setup.py --quiet install
# command to run tests
script:
  - pip uninstall --quiet --yes pytest py
  - python setup.py test
